# Site settings
author: MN
title: The Blog
header-img: img/home-bg.png
email: kmanoorib@gmail.com
copyright_name: MN
description: > # this means to ignore newlines until "baseurl:"
  A place for my thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MNGiit

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
